### ISSUE TITLE
Invalid response from API

### ISSUE THREAD

**Issue by ThrownLemon** [ConcealNetwork/conceal-cloud#12]
Looks like the API is responding with "result": "success" when it should be false

Request URL: https://api.wallet.conceal.network/api/wallet/pay
Request Method: POST
Response:
```json
{
	"result": "success",
	"message": {
		"success": false,
		"redirect": "https:\/\/conceal.cloud\/",
		"message": "Configuration error: Invalid or deleted client. Please contact the merchant."
	}
}
```

**Comment by kennycoder** [comment]
Thanks, will move to the next sprint :)

**Comment by krypt0x** [comment]
This issue has been fixed.
