### ISSUE TITLE
Timestamps are inconsistent in the API

### ISSUE THREAD

**Issue by ThrownLemon** [ConcealNetwork/conceal-cloud#13]
Seems like the UTC offset is missing on the Messages API endpoint.

**Wallets Response:**
https://api.wallet.conceal.network/api/wallet/unified
timestamp: "2020-07-11T04:30:09+02:00" _(Looks good)_

**Messages Response:**
https://api.wallet.conceal.network/api/wallet/messages
timestamp: "2020-07-11 04:30:09" _(Missing UTC)_

**Comment by krypt0x** [comment]
@ThrownLemon Have you got any feadback from @cryptomanel ? Is this resolved?

**Comment by cryptomanel** [comment]
Fixed and deployed since December.
