### ISSUE TITLE
Issues with transactions

### ISSUE THREAD

**Issue by ThrownLemon** [ConcealNetwork/conceal-cloud#15]
I think I've found two possibly related issues.

**Issue 1:**

Looks like the API isn't accepting valid transactions in some scenarios, for example:
**Balance:**  6.179906  - **Fee:** 0.001000
**Amount:** 6.178906

With the above transaction the API returns  **"Invalid amount. Try sending 0.001 - 0.002 less."** however this should be a valid transaction and there should be zero funds left in the wallet.

**Issue 2:**

Looks like the cloud wallet is using 5 decimal places instead of the correct 6 places.
This seems to cause a rounding issue when trying to max funds from your wallet.

![image](https://user-images.githubusercontent.com/4219774/90324073-7ac09880-dfad-11ea-8d86-26b6c47947c8.png)

**Comment by krypt0x** [comment]
resolved

**Comment by krypt0x** [comment]
closed
