### ISSUE TITLE
Avatar images are broken

### ISSUE THREAD

**Issue by ThrownLemon** [ConcealNetwork/conceal-cloud#16]
Avatar images do not load. Looks to sending the iamge with wrong MIME type.

https://conceal.cloud/cdn/images/<uuid>.jpg?
The script has an unsupported MIME type ('text/html').

![image](https://user-images.githubusercontent.com/4219774/90325892-984d2c80-dfc4-11ea-9b40-f82a72a7ef36.png)

**Comment by bomb-on** [comment]
This looks like an API issue, assigning to zem.

**Comment by krypt0x** [comment]
This issue has been fixed. Thank you.
